export { default as Login } from "./login";
export { default as Register } from "./register";
export { default as BindUser } from "./bind";
export { default as Recharge } from "./recharge";
export { default as Card } from "./card";
export { default as Home } from "./home";
export { default as Wallet } from "./wallet";
export { default as TranSaction } from "./transaction";
export { default as StoreDetail } from "./store-detail";
